# Generated by Django 5.2.1 on 2025-06-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slugy',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
