# Generated by Django 5.2.1 on 2025-06-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_slugy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slugy',
        ),
    ]
