# Generated by Django 5.0.2 on 2025-06-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_label_remove_question_answer_remove_question_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='questions', to='questions.label'),
        ),
    ]
