# Generated by Django 5.0.2 on 2025-06-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_label_options_label_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
