# Generated by Django 5.0.2 on 2025-06-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_label_category_alter_label_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('csharp', 'C#'), ('html', 'HTML'), ('css', 'CSS'), ('react', 'React'), ('angular', 'Angular'), ('vue', 'Vue.js'), ('django', 'Django'), ('flask', 'Flask'), ('spring', 'Spring'), ('express', 'Express.js'), ('laravel', 'Laravel'), ('sql', 'SQL'), ('mongodb', 'MongoDB'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('redis', 'Redis'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('aws', 'AWS'), ('azure', 'Azure'), ('git', 'Git'), ('algorithms', 'Algorithms'), ('data_structures', 'Data Structures'), ('design_patterns', 'Design Patterns'), ('oop', 'Object-Oriented Programming'), ('system_design', 'System Design'), ('problem_solving', 'Problem Solving'), ('code_quality', 'Code Quality'), ('algorithm_efficiency', 'Algorithm Efficiency'), ('debugging', 'Debugging Skills'), ('testing', 'Testing Knowledge'), ('technical_communication', 'Technical Communication'), ('documentation', 'Documentation'), ('code_review', 'Code Review'), ('team_collaboration', 'Team Collaboration'), ('knowledge_sharing', 'Knowledge Sharing'), ('clean_code', 'Clean Code'), ('security_awareness', 'Security Awareness'), ('performance_optimization', 'Performance Optimization'), ('scalability', 'Scalability'), ('maintainability', 'Maintainability'), ('time_management', 'Time Management'), ('adaptability', 'Adaptability'), ('learning_ability', 'Learning Ability'), ('attention_to_detail', 'Attention to Detail'), ('critical_thinking', 'Critical Thinking')], max_length=50, unique=True),
        ),
    ]
