# Generated by Django 5.0.2 on 2025-06-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_populate_field_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='labels',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
