# Generated by Django 5.0.2 on 2025-06-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_field_created_by_question_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
