# Generated by Django 5.0.2 on 2025-06-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_alter_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('Techincal', 'Techincal'), ('Soft Skill', 'Soft Skill')], default='Techincal', max_length=50),
        ),
    ]
