# Generated by Django 5.2.1 on 2025-06-13 18:01

import admin_dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('mail', models.CharField(max_length=300)),
                ('cv', models.FileField(upload_to=admin_dashboard.models.admin_upload)),
                ('phone', models.IntegerField(default=0)),
                ('fields', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Non-Completed', 'Non-Completed'), ('Processing', 'Processing')], max_length=100)),
                ('evaluation_point', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
    ]
