# Generated by Django 5.2.1 on 2025-06-13 18:17

import admin_dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=admin_dashboard.models.image_upload),
        ),
    ]
