# Generated by Django 5.2.1 on 2025-06-13 19:25

import admin_dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_dashboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='cv',
            field=models.FileField(max_length=500, upload_to=admin_dashboard.models.admin_upload),
        ),
    ]
