# Generated by Django 5.0.2 on 2025-06-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_alter_dashboard_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='status',
            field=models.CharField(choices=[('On Stage', 'On Stage'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Recommended', 'Recommended'), ('Expired', 'Expired')], max_length=100),
        ),
    ]
