# Generated by Django 5.0.2 on 2025-06-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_dashboard_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='mail',
            field=models.EmailField(max_length=300),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
