# Generated by Django 5.0.2 on 2025-06-26 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_alter_job_slug'),
        ('admin_dashboard', '0009_dashboard_evaluation_dec_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='fields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job.job'),
        ),
    ]
