# Generated by Django 5.0.2 on 2025-06-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_alter_dashboard_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='session_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
