# Generated by Django 5.0.2 on 2025-06-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0011_dashboard_session_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='cv_extractedText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
