# Generated by Django 5.0.2 on 2025-06-21 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 21, 18, 47, 44, 533125)),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='ended_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 21, 18, 47, 44, 533240)),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
