# Generated by Django 5.0.2 on 2025-06-21 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_scheduling', '0002_interviewsession_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 21, 18, 51, 18, 447484)),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 21, 18, 51, 18, 447608)),
        ),
    ]
