# Generated by Django 5.0.2 on 2025-06-21 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_scheduling', '0005_alter_interviewsession_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 21, 18, 55, 1, 45897)),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 21, 18, 55, 1, 46073)),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
