# Generated by Django 5.0.2 on 2025-06-22 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_scheduling', '0007_alter_interviewsession_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
