# Generated by Django 5.0.2 on 2025-06-26 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0011_dashboard_session_slug'),
        ('interview_scheduling', '0008_alter_interviewsession_scheduled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_consumed', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('candidate_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.dashboard')),
                ('interview_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_scheduling.interviewsession')),
            ],
        ),
    ]
