# Generated by Django 5.0.2 on 2025-06-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_scheduling', '0009_interview_data'),
        ('questions', '0015_field_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='selected_fields',
            field=models.ManyToManyField(to='questions.field'),
        ),
    ]
