# Generated by Django 5.0.2 on 2025-06-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_scheduling', '0010_interviewsession_selected_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='question_quantity',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
