# Generated by Django 5.0.2 on 2025-06-21 03:40

import Job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='logo',
            field=models.ImageField(blank=True, upload_to=Job.models.job_logo),
        ),
    ]
