# Generated by Django 5.0.2 on 2025-06-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_alter_job_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='requirements',
            new_name='qualifications',
        ),
        migrations.AddField(
            model_name='job',
            name='type_job',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(default=0),
        ),
    ]
